---
development:
  cloud_name: waraujo
  api_key: '719282358355756'
  api_secret: G6sg_zF22uXYQDurhdJ0YNLpAtk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: waraujo
  api_key: '719282358355756'
  api_secret: G6sg_zF22uXYQDurhdJ0YNLpAtk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: waraujo
  api_key: '719282358355756'
  api_secret: G6sg_zF22uXYQDurhdJ0YNLpAtk
  enhance_image_tag: true
  static_image_support: false
